In [ ]:
# https://github.com/VanChien11-02/Tri_tue_nhan_tao.git

In [1]:
# Máy hút bụi simple reflex agent
import numpy as np
import random

mt = np.random.randint(0, 2, size=(4, 4))
print(mt)
print()
x, y = 0, 0 # vi trí máy hút bụi
def P_moves(x,y):
    moves = []
    if x < 3:
        moves.append('D')
    if x > 0:
        moves.append('U')
    if y < 3:
        moves.append('R')
    if y > 0:
        moves.append('L')
    return moves

def P_action(x, y, action):
    if action == 'U':
        x -= 1
    elif action == 'D':
        x += 1
    elif action == 'L':
        y -= 1
    else:
        y += 1
    return x, y

while np.any(mt):
    state = mt[x][y]
    if state == 1:
        mt[x][y] = 0

    moves = P_moves(x, y)
    action = random.choice(moves)
    x,y = P_action(x, y, action)
    print(mt)
    print()

[[0 1 1 1]
 [0 0 1 0]
 [0 1 0 0]
 [1 0 0 1]]

[[0 1 1 1]
 [0 0 1 0]
 [0 1 0 0]
 [1 0 0 1]]

[[0 1 1 1]
 [0 0 1 0]
 [0 1 0 0]
 [1 0 0 1]]

[[0 1 1 1]
 [0 0 1 0]
 [0 1 0 0]
 [1 0 0 1]]

[[0 1 1 1]
 [0 0 1 0]
 [0 0 0 0]
 [1 0 0 1]]

[[0 1 1 1]
 [0 0 1 0]
 [0 0 0 0]
 [1 0 0 1]]

[[0 1 1 1]
 [0 0 1 0]
 [0 0 0 0]
 [0 0 0 1]]

[[0 1 1 1]
 [0 0 1 0]
 [0 0 0 0]
 [0 0 0 1]]

[[0 1 1 1]
 [0 0 1 0]
 [0 0 0 0]
 [0 0 0 1]]

[[0 1 1 1]
 [0 0 1 0]
 [0 0 0 0]
 [0 0 0 1]]

[[0 1 1 1]
 [0 0 1 0]
 [0 0 0 0]
 [0 0 0 1]]

[[0 1 1 1]
 [0 0 1 0]
 [0 0 0 0]
 [0 0 0 1]]

[[0 1 1 1]
 [0 0 1 0]
 [0 0 0 0]
 [0 0 0 1]]

[[0 1 1 1]
 [0 0 1 0]
 [0 0 0 0]
 [0 0 0 1]]

[[0 1 1 1]
 [0 0 1 0]
 [0 0 0 0]
 [0 0 0 1]]

[[0 1 1 1]
 [0 0 1 0]
 [0 0 0 0]
 [0 0 0 1]]

[[0 1 1 1]
 [0 0 1 0]
 [0 0 0 0]
 [0 0 0 1]]

[[0 1 1 1]
 [0 0 1 0]
 [0 0 0 0]
 [0 0 0 1]]

[[0 1 1 1]
 [0 0 1 0]
 [0 0 0 0]
 [0 0 0 1]]

[[0 1 1 1]
 [0 0 1 0]
 [0 0 0 0]
 [0 0 0 1]]

[[0 1 1 1]
 [0 0 1 0]
 [0 0 0 0]
 [0 0 0 1]]

[[0 1 1 1]
 [0 0 1 0]
 [0 0 0 0]
 

In [2]:
# máy hút bụi model-base-reflex-agent
import numpy as np
import random

mt = np.random.randint(0, 2, size=(4, 4))
print(mt)
print()
x, y = 0, 0 # vi trí máy hút bụi
def P_moves(x,y):
    moves = []
    if x < 3:
        moves.append('D')
    if x > 0:
        moves.append('U')
    if y < 3:
        moves.append('R')
    if y > 0:
        moves.append('L')
    return moves

def P_action(x, y, action):
    if action == 'U':
        x -= 1
    elif action == 'D':
        x += 1
    elif action == 'L':
        y -= 1
    else:
        y += 1
    return x, y


while np.any(mt):
    state = mt[x][y]
    if state == 1:
        mt[x][y] = 0

    moves = P_moves(x, y)
    action = random.choice(moves)
    x,y = P_action(x, y, action)
    print(mt)
    print()



[[1 1 1 1]
 [1 1 0 0]
 [0 1 0 0]
 [1 1 0 1]]

[[0 1 1 1]
 [1 1 0 0]
 [0 1 0 0]
 [1 1 0 1]]

[[0 0 1 1]
 [1 1 0 0]
 [0 1 0 0]
 [1 1 0 1]]

[[0 0 1 1]
 [1 1 0 0]
 [0 1 0 0]
 [1 1 0 1]]

[[0 0 1 1]
 [0 1 0 0]
 [0 1 0 0]
 [1 1 0 1]]

[[0 0 1 1]
 [0 1 0 0]
 [0 1 0 0]
 [1 1 0 1]]

[[0 0 1 1]
 [0 1 0 0]
 [0 0 0 0]
 [1 1 0 1]]

[[0 0 1 1]
 [0 0 0 0]
 [0 0 0 0]
 [1 1 0 1]]

[[0 0 1 1]
 [0 0 0 0]
 [0 0 0 0]
 [1 1 0 1]]

[[0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]
 [1 1 0 1]]

[[0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]
 [1 1 0 1]]

[[0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]
 [1 1 0 1]]

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 1 0 1]]

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 1 0 1]]

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 1 0 1]]

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 1 0 1]]

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 1 0 1]]

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 0 1]]

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 0 1]]

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 0 0]]

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 0 0]]

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 

In [3]:
# game 8 puzzle model-base-reflex-agent
import random

nums  = list(range(9))
random.shuffle(nums)
mt = [nums[0:3], nums[3:6], nums[6:9]]
print(mt)
print()

def check_null(mt):
    for i in range(3):
        for j in range(3):
            if mt[i][j] == 0:
                return i, j
    return None


def P_moves(x,y):
    moves = []
    if x < 2:
        moves.append('D')
    if x > 0:
        moves.append('U')
    if y < 2:
        moves.append('R')
    if y > 0:
        moves.append('L')
    return moves

def P_action(x, y, action):
    if action == 'U':
        x -= 1
    elif action == 'D':
        x += 1
    elif action == 'L':
        y -= 1
    else:
        y += 1
    return x, y

def old_action(action):
    if action == 'U':
        return 'D'
    elif action == 'D':
        return 'U'
    elif action == 'L':
        return 'R'
    return 'L'


nx, ny = check_null(mt)
old_state = ''
while mt != [[1, 2, 3], [4, 5, 6], [7, 8, 0]]:
    moves = P_moves(nx, ny)
    if old_state in moves:
        moves.remove(old_state)
    action = random.choice(moves)
    old_state = old_action(action)
    x, y = P_action(nx, ny, action)
    mt[nx][ny], mt[x][y] = mt[x][y], mt[nx][ny]
    nx, ny = x, y
    print(mt)
    print()



[[1, 8, 5], [0, 2, 3], [6, 4, 7]]

[[1, 8, 5], [2, 0, 3], [6, 4, 7]]

[[1, 8, 5], [2, 4, 3], [6, 0, 7]]

[[1, 8, 5], [2, 4, 3], [0, 6, 7]]

[[1, 8, 5], [0, 4, 3], [2, 6, 7]]

[[1, 8, 5], [4, 0, 3], [2, 6, 7]]

[[1, 8, 5], [4, 3, 0], [2, 6, 7]]

[[1, 8, 0], [4, 3, 5], [2, 6, 7]]

[[1, 0, 8], [4, 3, 5], [2, 6, 7]]

[[0, 1, 8], [4, 3, 5], [2, 6, 7]]

[[4, 1, 8], [0, 3, 5], [2, 6, 7]]

[[4, 1, 8], [2, 3, 5], [0, 6, 7]]

[[4, 1, 8], [2, 3, 5], [6, 0, 7]]

[[4, 1, 8], [2, 3, 5], [6, 7, 0]]

[[4, 1, 8], [2, 3, 0], [6, 7, 5]]

[[4, 1, 0], [2, 3, 8], [6, 7, 5]]

[[4, 0, 1], [2, 3, 8], [6, 7, 5]]

[[0, 4, 1], [2, 3, 8], [6, 7, 5]]

[[2, 4, 1], [0, 3, 8], [6, 7, 5]]

[[2, 4, 1], [3, 0, 8], [6, 7, 5]]

[[2, 0, 1], [3, 4, 8], [6, 7, 5]]

[[2, 1, 0], [3, 4, 8], [6, 7, 5]]

[[2, 1, 8], [3, 4, 0], [6, 7, 5]]

[[2, 1, 8], [3, 4, 5], [6, 7, 0]]

[[2, 1, 8], [3, 4, 5], [6, 0, 7]]

[[2, 1, 8], [3, 4, 5], [0, 6, 7]]

[[2, 1, 8], [0, 4, 5], [3, 6, 7]]

[[0, 1, 8], [2, 4, 5], [3, 6, 7]]

[[1, 0, 8], [2, 4, 5